# Synchronises the GitHub repository with a remote repository (SYNC_REMOTE), using a SSH key pair.
# The private key is stored in SYNC_PRIVATE_KEY, the public key is registered on the remote repository.
# The remote's host keys are stored in SYNC_REMOTE_KEYSCAN (see ssh-keyscan(1)).
name: Sync
on:
  # Runs every day at midnight.
  schedule:
    - cron: 0 0 * * *
  # Can be ran manually.
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Retrieves all the history, not just the last commit.
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          # Configures the private key for the remote.
          ssh-private-key: ${{secrets.SYNC_PRIVATE_KEY}}
      - run: echo "${{secrets.SYNC_REMOTE_KEYSCAN}}" >> ~/.ssh/known_hosts
      - run: git push --prune ${{secrets.SYNC_REMOTE}} "+refs/remotes/origin/*:refs/heads/*" "+refs/tags/*:refs/tags/*"
